name: Auto Tag Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
          echo "latest_tag=$tag" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: bump
        run: |
          version=${{ steps.get_tag.outputs.latest_tag }}
          version=${version#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          echo "new_tag=v$major.$minor.$patch" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}
